#!/usr/bin/env bash

# if not coming from .bash_profile and .bash_profile exists
if [[ -z "${COMING_FROM_BASH_PROFILE}" && -f "${HOME}/.bash_profile" ]]; then
    export COMING_FROM_BASHRC=true
    # shellcheck disable=SC1091
    source "${HOME}/.bash_profile"
    unset COMING_FROM_BASHRC
fi

# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) return ;;
esac

#  ▄▄▄▄    ▄▄▄        ██████  ██░ ██     ██▓▄▄▄█████▓
# ▓█████▄ ▒████▄    ▒██    ▒ ▓██░ ██▒   ▓██▒▓  ██▒ ▓▒
# ▒██▒ ▄██▒██  ▀█▄  ░ ▓██▄   ▒██▀▀██░   ▒██▒▒ ▓██░ ▒░
# ▒██░█▀  ░██▄▄▄▄██   ▒   ██▒░▓█ ░██    ░██░░ ▓██▓ ░
# ░▓█  ▀█▓ ▓█   ▓██▒▒██████▒▒░▓█▒░██▓   ░██░  ▒██▒ ░
# ░▒▓███▀▒ ▒▒   ▓▒█░▒ ▒▓▒ ▒ ░ ▒ ░░▒░▒   ░▓    ▒ ░░
# ▒░▒   ░   ▒   ▒▒ ░░ ░▒  ░ ░ ▒ ░▒░ ░    ▒ ░    ░
#  ░    ░   ░   ▒   ░  ░  ░   ░  ░░ ░    ▒ ░  ░
#  ░            ░  ░      ░   ░  ░  ░    ░
#       ░

# Path to the bash it configuration
export BASH_IT="${HOME}/.bash_it"

# Lock and Load a custom theme file
export BASH_IT_THEME='easy'

# Don't check mail when opening terminal.
unset MAILCHECK

# Project directory
# shellcheck disable=SC2034
BASH_IT_PROJECT_PATHS="${WORKSPACE_DIR}"

# Version control status checking
export SCM_CHECK=true

# Load Bash It
if [[ -f "${BASH_IT}/bash_it.sh" ]]; then
    # shellcheck disable=SC1091
    source "${BASH_IT}/bash_it.sh"
fi
