#!/bin/sh
# vim: ft=sh

# .testcontainers.properties is sometimes modified by external tools
# and thus we only manage the properties we care about (podman support)

existing_file=$(cat)

trap 'printf "%s\n" "$existing_file"' EXIT

if ! command -v podman >/dev/null 2>&1; then
  exit 0
fi

set_property() {
  key="$1"
  value="$2"
  if echo "$existing_file" | grep -q "^${key}="; then
    existing_file=$(echo "$existing_file" | sed "s|^${key}=.*|${key}=${value}|")
  else
    if [ -n "$existing_file" ]; then
      existing_file="${existing_file}
${key}=${value}"
    else
      existing_file="${key}=${value}"
    fi
  fi
}

case "$(uname -s)" in
Darwin*)
  docker_host="unix://$(podman machine inspect --format '{{.ConnectionInfo.PodmanSocket.Path}}')"
  ;;
Linux*)
  docker_host="unix://${XDG_RUNTIME_DIR}/podman/podman.sock"
  ;;
*)
  exit 0
  ;;
esac

set_property "docker.host" "$docker_host"
set_property "ryuk.disabled" "true"
set_property "testcontainers.reuse.enable" "true"
