return {
  -- stylua: ignore start
  lspkind = {
    Array         = " ",
    Boolean       = "󰨙 ",
    Class         = " ",
    Constant      = "󰏿 ",
    Constructor   = " ",
    Enum          = " ",
    EnumMember    = " ",
    Event         = " ",
    Field         = " ",
    File          = "󰈚",
    Function      = "󰊕 ",
    Interface     = " ",
    Key           = " ",
    Method        = "󰊕 ",
    Module        = " ",
    Namespace     = "󰦮 ",
    Null          = "󰟢",
    Number        = "󰎠 ",
    Object        = " ",
    Operator      = " ",
    Package       = " ",
    Property      = "󰜢",
    String        = " ",
    Struct        = "󰙅",
    TypeParameter = " ",
    Variable      = "󰀫 ",
    Text          = "󰉿",
    Unit          = "󰑭",
    Value         = "󰎠",
    Keyword       = "󰌋",
    Snippet       = "",
    Color         = "󰏘",
    Reference     = "󰈇",
    Folder        = "󰉋",
    Table         = "",
    Tag           = "",
    Supermaven    = "",
    Calendar      = "",
    Watch         = "󰥔",
    Copilot       = "",
    Codeium       = "",
    TabNine       = "",
    BladeNav      = "",
  },
  -- stylua: ignore end
  dap = {
    Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = ".>",
  },
  gitsigns = {
    delete = { text = "󰍵" },
    changedelete = { text = "󱕖" },
  },
  diagnostic = {
    error = "󰅙 ",
    warn = " ",
    info = "󰋼 ",
    hint = "󰌵 ",
  },
  separators = {
    left = " ",
    right = " ",
  },
}
